### ISSUE TITLE
How the triples.train.small is generated

### ISSUE THREAD

**Issue by hanshuguang** [microsoft/MSMARCO-Passage-Ranking#10]
Hi, there:

I have a question about how the triples.train.small is generated, in the statement, it says

"The triples.train.<size>.tsv are two files that we have created as an easy to consume training dataset. Each line of the TSV contains querytext, A relevant passage, and an non-relevant passage all separated by \t. The only difference between triples.train.full.tsv and triples.train.small.tsv is the smaller is ~10% of the overall size since the full sized train is > 270gbs."

- Does `triples.train.small` contain all of the queries as ``triples.full.small``?
- For each query (in `triples.train.small`), how non-relevant passages were selected? Randomly?

**Comment by spacemanidol** [comment]
Yes and yes.

**Comment by rodrigonogueira4** [comment]
Hi @spacemanidol,

I was looking at triples.train.small.tsv and it does not seem that the negatives are completely random wrt the query:

_Query: is a little caffeine ok during pregnancy
Negative: It is generally safe for pregnant women to eat chocolate because studies have shown to prove certain benefits of eating chocolate during pregnancy. However, pregnant women should ensure their caffeine intake is below 200 mg per day._

Maybe you mean randomly selecting a negative from the top-1000 returned by BM25?
