### ISSUE TITLE
relevant-passages section of readme said there are 5 qrels files, but I only see two, the other three are query files

### ISSUE THREAD

**Issue by Santosh-Gupta** [microsoft/MSMARCO-Passage-Ranking#19]
https://github.com/microsoft/MSMARCO-Passage-Ranking#relevant-passages

In the relevant-passages section, it says that the file located here https://msmarco.blob.core.windows.net/msmarcoranking/collectionandqueries.tar.gz

contains the following 

>     7437 qrels.dev.small.tsv
>    59273 qrels.dev.tsv
>     7304 qrels.eval.small.tsv
>    59187 qrels.eval.tsv
>   532761 qrels.train.tsv
>   665962 total

However, these are the files I got instead

> collection.tsv
> qrels.dev.small.tsv
> qrels.train.tsv
> queries.dev.small.tsv
> queries.dev.tsv
> queries.eval.small.tsv
> queries.eval.tsv
> queries.train.tsv

Are there missing qrels files, or does the read.me have some typos?

I also had a few other questions about the data for the passage ranking/retrieval data:

Are the triples training data created from the purely the passage texts, query text, and the qrels relevance ranking? Are the negative samples selected at random (excluding the positive passage)?

the qrels data has a total of 532,761(train) +  59,273(dev) relevance rankings, but there are about 1 million queries and 8.8 million passages. So does the relevance data exclude a majority of the questions/passages?

**Comment by spacemanidol** [comment]
Hey, sorry for the delay. 

The eval qrels have been deliberately held out for evaluation and thus aren't available publicly

Triples are built entirely by qrels and negative samples are selected by selecting something not selected by b25(top1000) at random as the negative samples. 

The relevance information has this numerical difference because around 1/3 ish of the queries did not have an answer. In the original MSMARCO QnA dataset, there is a high distribution of queries that don't have an answer given the passages and thus we do not have a positive ranking signal. These queries have been removed from the ranking task but still exist for the purposes of term mining.
